"use node";

import { action } from "./_generated/server";
import { internal } from "./_generated/api";
import { v } from "convex/values";
import { Resend } from "resend";
import type { Id } from "./_generated/dataModel";

export const sendScopeEmail = action({
  args: {
    projectId: v.id("projects"),
    storageId: v.string(),
    recipientEmail: v.string(),
    filename: v.string(),
  },
  handler: async (ctx, args) => {
    const identity = await ctx.auth.getUserIdentity();
    if (!identity) throw new Error("Not authenticated");

    // Verify project ownership + paid status
    const project = await ctx.runQuery(internal.projects.getProjectInternal, {
      projectId: args.projectId,
    });
    if (!project) throw new Error("Project not found");
    if (project.status !== "paid") throw new Error("Project must be paid");

    const apiKey = process.env.RESEND_API_KEY;
    if (!apiKey) throw new Error("RESEND_API_KEY not configured");

    // Get the storage URL for the uploaded PDF
    const storageUrl = await ctx.storage.getUrl(args.storageId as Id<"_storage">);
    if (!storageUrl) throw new Error("PDF file not found in storage");

    const label =
      (project.projectType?.charAt(0).toUpperCase() ?? "") +
      (project.projectType?.slice(1) ?? "");
    const location = [project.propertySuburb, project.propertyState]
      .filter(Boolean)
      .join(", ");

    const resend = new Resend(apiKey);

    const { error } = await resend.emails.send({
      from: "ScopeAI <noreply@scopeai.com.au>",
      to: [args.recipientEmail],
      subject: `Your ${label} Renovation Scope of Works`,
      html: `
        <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 560px; margin: 0 auto; padding: 40px 20px;">
          <div style="border-bottom: 3px solid #14B8A6; padding-bottom: 16px; margin-bottom: 24px;">
            <h1 style="font-size: 24px; font-weight: 700; color: #14B8A6; margin: 0;">ScopeAI</h1>
          </div>
          <h2 style="font-size: 20px; font-weight: 600; color: #111827; margin: 0 0 8px;">
            Your ${label} Renovation Scope
          </h2>
          ${location ? `<p style="font-size: 14px; color: #6B7280; margin: 0 0 24px;">${location}</p>` : ""}
          <p style="font-size: 15px; color: #374151; line-height: 1.6; margin: 0 0 24px;">
            Your scope of works is attached as a PDF. This document includes all trade scopes,
            sequencing plan, and coordination checklist for your renovation project.
          </p>
          <p style="font-size: 15px; color: #374151; line-height: 1.6; margin: 0 0 24px;">
            Forward this PDF to your tradies to get comparable quotes.
          </p>
          <hr style="border: none; border-top: 1px solid #E5E7EB; margin: 32px 0;" />
          <p style="font-size: 12px; color: #9CA3AF; margin: 0;">
            Generated by ScopeAI &mdash; scopeai.com.au
          </p>
        </div>
      `,
      attachments: [
        {
          path: storageUrl,
          filename: args.filename,
        },
      ],
    });

    if (error) {
      console.error("Resend error:", error);
      throw new Error(`Failed to send email: ${error.message}`);
    }

    return { success: true };
  },
});
