import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-16 sm:px-6 sm:py-24">
      <h1 className="text-3xl font-bold tracking-tight">Terms of Service</h1>
      <p className="mt-2 text-sm text-muted-foreground">
        Last updated: February 2026
      </p>

      <div className="mt-10 space-y-8 text-sm leading-relaxed text-muted-foreground [&_h2]:text-base [&_h2]:font-semibold [&_h2]:text-foreground [&_h2]:mb-3 [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:space-y-1">
        <section>
          <h2>1. Scope of Service</h2>
          <p>
            ScopeAI is an AI-powered tool that generates renovation scope-of-works
            documents based on photos and information you provide. The service is
            designed for Australian residential renovations including kitchens,
            bathrooms, laundries, living areas, and outdoor spaces.
          </p>
        </section>

        <section>
          <h2>2. Not Professional Advice</h2>
          <p>
            Scope documents generated by ScopeAI are intended as a guide to help
            you communicate your renovation requirements to tradespeople. They are
            <strong> not a substitute for professional advice</strong> from licensed
            builders, architects, engineers, or other qualified professionals. You
            should always verify scope details with your chosen tradespeople before
            commencing work.
          </p>
        </section>

        <section>
          <h2>3. Accuracy &amp; Limitations</h2>
          <p>
            While we strive for accuracy, AI-generated scopes may contain errors
            or omissions. ScopeAI does not guarantee:
          </p>
          <ul className="mt-2">
            <li>Completeness of scope items for your specific project.</li>
            <li>Accuracy of provisional cost sum (PC Sum) estimates.</li>
            <li>Compliance with all local council or state regulations.</li>
            <li>Suitability for your specific property conditions.</li>
          </ul>
        </section>

        <section>
          <h2>4. Payment Terms</h2>
          <p>
            Payments are processed securely via Stripe. All prices are in
            Australian Dollars (AUD) and include GST where applicable. Once a scope
            package has been generated and payment processed, refunds are provided
            at our discretion — please contact us if you experience issues.
          </p>
        </section>

        <section>
          <h2>5. Your Content</h2>
          <p>
            You retain ownership of photos and information you upload. By using
            ScopeAI, you grant us a limited licence to process your content using
            AI services (Google Gemini) solely for the purpose of generating your
            scope documents. We do not use your content for training AI models.
          </p>
        </section>

        <section>
          <h2>6. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by Australian law, ScopeAI and its
            operators shall not be liable for any indirect, incidental, special, or
            consequential damages arising from your use of the service, including
            but not limited to costs arising from reliance on generated scope
            documents.
          </p>
        </section>

        <section>
          <h2>7. Account Termination</h2>
          <p>
            You may delete your account at any time via account settings. We
            reserve the right to suspend or terminate accounts that violate these
            terms or use the service in bad faith.
          </p>
        </section>

        <section>
          <h2>8. Changes to Terms</h2>
          <p>
            We may update these terms from time to time. Continued use of ScopeAI
            after changes constitutes acceptance of the updated terms.
          </p>
        </section>

        <section>
          <h2>9. Governing Law</h2>
          <p>
            These terms are governed by the laws of New South Wales, Australia.
          </p>
        </section>

        <section>
          <h2>10. Contact</h2>
          <p>
            If you have questions about these terms, contact us at{" "}
            <a
              href="mailto:hello@scopeai.com.au"
              className="text-primary underline underline-offset-2"
            >
              hello@scopeai.com.au
            </a>
            .
          </p>
        </section>
      </div>
    </div>
  );
}
