import React from "react";
import { Document, Page, View, Text } from "@react-pdf/renderer";
import { styles, TEAL, MUTED, BORDER, BG_ALT, WHITE, DARK } from "./styles";
import type {
  ScopeItem,
  PCSum,
  SequencingPhase,
  CoordinationItem,
  TradeType,
} from "@/types";
import { TRADE_META } from "@/lib/trades";

interface TradeData {
  tradeType: string;
  title: string;
  items: ScopeItem[];
  exclusions: string[];
  pcSums?: PCSum[];
  complianceNotes?: string;
  warnings?: string[];
  notes?: string;
}

interface ScopeDocumentProps {
  projectType: string;
  suburb?: string;
  state?: string;
  generatedAt?: number;
  scopes: TradeData[];
  sequencing: { phases: SequencingPhase[]; totalDurationEstimate: string } | null;
  coordination: { items: CoordinationItem[] } | null;
}

function Header({ projectType, suburb, state, generatedAt }: {
  projectType: string;
  suburb?: string;
  state?: string;
  generatedAt?: number;
}) {
  const label = projectType.charAt(0).toUpperCase() + projectType.slice(1);
  const location = [suburb, state].filter(Boolean).join(", ");
  const date = generatedAt
    ? new Date(generatedAt).toLocaleDateString("en-AU", { day: "numeric", month: "short", year: "numeric" })
    : new Date().toLocaleDateString("en-AU", { day: "numeric", month: "short", year: "numeric" });

  return (
    <>
      <View style={styles.headerBar} fixed />
      <View style={styles.headerRow} fixed>
        <Text style={styles.headerBrand}>ScopeAI</Text>
        <View>
          <Text style={styles.headerMeta}>{label} Renovation</Text>
          {location && <Text style={styles.headerMeta}>{location}</Text>}
          <Text style={styles.headerMeta}>{date}</Text>
        </View>
      </View>
    </>
  );
}

function Footer() {
  return (
    <View style={styles.footer} fixed>
      <Text>Generated by ScopeAI — scopeai.com.au</Text>
      <Text render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} />
    </View>
  );
}

function TradeSection({ scope }: { scope: TradeData }) {
  const meta = TRADE_META[scope.tradeType as TradeType];
  const includedItems = scope.items.filter((it) => it.included);
  const excludedCount = scope.items.length - includedItems.length;

  // Group by category
  const groups = new Map<string, ScopeItem[]>();
  includedItems.forEach((item) => {
    const cat = item.category || "General";
    if (!groups.has(cat)) groups.set(cat, []);
    groups.get(cat)!.push(item);
  });

  return (
    <View>
      <Text style={styles.sectionTitle}>
        {meta?.icon ?? ""} {scope.title}
      </Text>

      {Array.from(groups.entries()).map(([category, items]) => (
        <View key={category} wrap={false}>
          <Text style={styles.categoryTitle}>{category}</Text>
          {items.map((item, i) => (
            <View
              key={item.id}
              style={[styles.itemRow, i % 2 === 1 ? styles.itemRowAlt : {}]}
            >
              <Text style={styles.itemBullet}>•</Text>
              <View style={styles.itemContent}>
                <Text style={styles.itemName}>{item.item}</Text>
                <Text style={styles.itemSpec}>{item.specification}</Text>
                {item.complianceNote && (
                  <Text style={styles.itemCompliance}>{item.complianceNote}</Text>
                )}
              </View>
            </View>
          ))}
        </View>
      ))}

      {excludedCount > 0 && (
        <Text style={styles.excludedNote}>
          {excludedCount} item{excludedCount !== 1 ? "s" : ""} excluded by homeowner and not shown
        </Text>
      )}

      {/* Exclusions */}
      {scope.exclusions.length > 0 && (
        <View style={{ marginTop: 8 }}>
          <Text style={styles.categoryTitle}>Exclusions</Text>
          {scope.exclusions.map((ex, i) => (
            <View key={i} style={styles.exclusionItem}>
              <Text style={styles.exclusionBullet}>✕</Text>
              <Text style={styles.exclusionText}>{ex}</Text>
            </View>
          ))}
        </View>
      )}

      {/* PC Sums */}
      {scope.pcSums && scope.pcSums.length > 0 && (
        <View style={{ marginTop: 10 }}>
          <Text style={styles.categoryTitle}>Provisional Cost Sums</Text>
          <View style={styles.tableHeader}>
            <Text style={[styles.tableHeaderText, { flex: 3 }]}>Item</Text>
            <Text style={[styles.tableHeaderText, { flex: 1, textAlign: "center" }]}>Qty</Text>
            <Text style={[styles.tableHeaderText, { flex: 1, textAlign: "right" }]}>Low</Text>
            <Text style={[styles.tableHeaderText, { flex: 1, textAlign: "right" }]}>High</Text>
          </View>
          {scope.pcSums.map((pc, i) => (
            <View key={i} style={[styles.tableRow, i % 2 === 1 ? styles.tableRowAlt : {}]}>
              <Text style={[styles.tableCell, { flex: 3 }]}>
                {pc.item} {pc.unit ? `(${pc.unit})` : ""}
              </Text>
              <Text style={[styles.tableCell, { flex: 1, textAlign: "center" }]}>
                {pc.quantity ?? "-"}
              </Text>
              <Text style={[styles.tableCell, { flex: 1, textAlign: "right" }]}>
                {pc.budgetLow}
              </Text>
              <Text style={[styles.tableCell, { flex: 1, textAlign: "right" }]}>
                {pc.budgetHigh}
              </Text>
            </View>
          ))}
        </View>
      )}

      {/* Warnings */}
      {scope.warnings && scope.warnings.length > 0 && (
        <View style={styles.warningBox} wrap={false}>
          <Text style={styles.warningTitle}>Warnings</Text>
          {scope.warnings.map((w, i) => (
            <Text key={i} style={styles.warningItem}>• {w}</Text>
          ))}
        </View>
      )}

      {/* Compliance */}
      {scope.complianceNotes && (
        <View style={styles.notesBox} wrap={false}>
          <Text style={[styles.notesText, { fontFamily: "Helvetica-Bold", marginBottom: 2 }]}>
            Compliance
          </Text>
          <Text style={styles.notesText}>{scope.complianceNotes}</Text>
        </View>
      )}

      {/* Notes */}
      {scope.notes && (
        <View style={styles.notesBox} wrap={false}>
          <Text style={styles.notesText}>{scope.notes}</Text>
        </View>
      )}
    </View>
  );
}

function SequencingSection({ phases, totalDuration }: {
  phases: SequencingPhase[];
  totalDuration: string;
}) {
  return (
    <View>
      <Text style={styles.sectionTitle}>Sequencing Plan</Text>
      <Text style={{ fontSize: 9, color: MUTED, marginBottom: 8 }}>
        Estimated total duration: {totalDuration}
      </Text>

      <View style={styles.tableHeader}>
        <Text style={[styles.tableHeaderText, { width: 36 }]}>Phase</Text>
        <Text style={[styles.tableHeaderText, { flex: 2 }]}>Trade</Text>
        <Text style={[styles.tableHeaderText, { flex: 1 }]}>Duration</Text>
        <Text style={[styles.tableHeaderText, { flex: 2 }]}>Dependencies</Text>
      </View>
      {phases.map((phase, i) => (
        <View key={i} style={[styles.phaseRow, i % 2 === 1 ? styles.tableRowAlt : {}]}>
          <Text style={[styles.tableCell, { width: 36 }]}>{phase.phase}</Text>
          <View style={{ flex: 2, flexDirection: "row", alignItems: "center" }}>
            <Text style={styles.tableCell}>{phase.trade}</Text>
            {phase.isHoldPoint && (
              <View style={styles.holdPointBadge}>
                <Text style={styles.holdPointText}>HOLD</Text>
              </View>
            )}
          </View>
          <Text style={[styles.tableCell, { flex: 1 }]}>{phase.duration}</Text>
          <Text style={[styles.tableCell, { flex: 2, color: MUTED }]}>
            {phase.dependencies || "—"}
          </Text>
        </View>
      ))}
    </View>
  );
}

function CoordinationSection({ items }: { items: CoordinationItem[] }) {
  return (
    <View>
      <Text style={styles.sectionTitle}>Coordination Checklist</Text>

      <View style={styles.tableHeader}>
        <Text style={[styles.tableHeaderText, { width: 10 }]} />
        <Text style={[styles.tableHeaderText, { flex: 1 }]}>Before</Text>
        <Text style={[styles.tableHeaderText, { flex: 1 }]}>After</Text>
        <Text style={[styles.tableHeaderText, { flex: 3 }]}>Check</Text>
      </View>
      {items.map((item, i) => (
        <View key={i} style={[styles.coordRow, i % 2 === 1 ? styles.tableRowAlt : {}]}>
          <View style={{ width: 10 }}>
            {item.critical && <View style={styles.criticalDot} />}
          </View>
          <Text style={[styles.tableCell, { flex: 1 }]}>{item.beforeTrade}</Text>
          <Text style={[styles.tableCell, { flex: 1 }]}>{item.afterTrade}</Text>
          <Text style={[styles.tableCell, { flex: 3 }]}>{item.check}</Text>
        </View>
      ))}
    </View>
  );
}

export function ScopeDocument({
  projectType,
  suburb,
  state,
  generatedAt,
  scopes,
  sequencing,
  coordination,
}: ScopeDocumentProps) {
  const label = projectType.charAt(0).toUpperCase() + projectType.slice(1);

  return (
    <Document
      title={`${label} Renovation — Scope of Works`}
      author="ScopeAI"
      subject="Renovation Scope of Works"
    >
      <Page size="A4" style={styles.page}>
        <Header
          projectType={projectType}
          suburb={suburb}
          state={state}
          generatedAt={generatedAt}
        />

        <Text style={styles.pageTitle}>{label} Renovation — Scope of Works</Text>
        <Text style={styles.pageSubtitle}>
          {scopes.length} trade{scopes.length !== 1 ? "s" : ""} included
        </Text>

        {scopes.map((scope) => (
          <TradeSection key={scope.tradeType} scope={scope} />
        ))}

        {sequencing && (
          <SequencingSection
            phases={sequencing.phases}
            totalDuration={sequencing.totalDurationEstimate}
          />
        )}

        {coordination && coordination.items.length > 0 && (
          <CoordinationSection items={coordination.items} />
        )}

        <Footer />
      </Page>
    </Document>
  );
}
