import type { Question } from "@/types";

export const bathroomQuestions: Question[] = [
  {
    id: "layout_change",
    question: "Are you changing the bathroom layout?",
    why: "Moving the toilet, shower, or vanity changes the plumbing rough-in significantly. A layout change can double the plumbing cost.",
    options: [
      { label: "No — keeping same layout" },
      { label: "Minor tweaks — moving vanity or shower slightly" },
      { label: "Major redesign — completely different layout" },
      { label: "Not sure yet" },
    ],
    multiSelect: false,
    defaultIfSkipped: "Minor tweaks — moving vanity or shower slightly",
  },
  {
    id: "shower_type",
    question: "What type of shower?",
    why: "Walk-in showers, shower-over-bath, and separate shower stalls have different waterproofing, plumbing, and tiling requirements.",
    options: [
      { label: "Walk-in shower (frameless screen)" },
      { label: "Shower over bath" },
      { label: "Enclosed shower cubicle" },
      { label: "Wet room (no screen, open shower)" },
    ],
    multiSelect: false,
    defaultIfSkipped: "Walk-in shower (frameless screen)",
  },
  {
    id: "shower_drain",
    question: "Shower drain preference?",
    why: "Linear (strip) drains look modern but require more precise floor falls. Centre drains are simpler and cheaper to install.",
    options: [
      { label: "Centre drain (standard)" },
      { label: "Linear/strip drain (modern look)" },
      { label: "Tile-insert drain (hidden)" },
      { label: "Not sure" },
    ],
    multiSelect: false,
    defaultIfSkipped: "Centre drain (standard)",
  },
  {
    id: "bath",
    question: "Will you have a bath?",
    why: "Freestanding baths need floor-mounted or wall-mounted tapware and specific waste positioning. Built-in baths need a surround and tiling.",
    options: [
      { label: "Yes — freestanding" },
      { label: "Yes — built-in/drop-in" },
      { label: "Shower over bath (combined)" },
      { label: "No bath" },
    ],
    multiSelect: false,
    defaultIfSkipped: "No bath",
  },
  {
    id: "toilet_type",
    question: "What type of toilet?",
    why: "Concealed cisterns (wall-faced or wall-hung) need framing and plumbing behind the wall. Standard close-coupled toilets are simpler.",
    options: [
      { label: "Standard close-coupled" },
      { label: "Wall-faced (concealed cistern)" },
      { label: "Wall-hung (floating)" },
      { label: "Keeping existing toilet" },
    ],
    multiSelect: false,
    defaultIfSkipped: "Wall-faced (concealed cistern)",
  },
  {
    id: "vanity_type",
    question: "What type of vanity?",
    why: "Wall-hung vanities need structural support behind the wall. Floor-standing is simpler. Double basins need wider plumbing rough-in.",
    options: [
      { label: "Wall-hung — single basin" },
      { label: "Wall-hung — double basin" },
      { label: "Floor-standing — single basin" },
      { label: "Floor-standing — double basin" },
      { label: "Not decided yet" },
    ],
    multiSelect: false,
    defaultIfSkipped: "Wall-hung — single basin",
  },
  {
    id: "heated_features",
    question: "Any heated features?",
    why: "Heated towel rails need an electrical circuit. In-floor heating needs either electrical mats (electrician) or hydronic pipes (plumber), and must be installed BEFORE tiling.",
    options: [
      { label: "Heated towel rail" },
      { label: "In-floor heating" },
      { label: "Both" },
      { label: "No heated features" },
    ],
    multiSelect: false,
    defaultIfSkipped: "Heated towel rail",
  },
  {
    id: "ventilation",
    question: "Exhaust fan type?",
    why: "Ducted fans vent moisture outside (recommended). Recirculating fans are simpler but less effective. Timer or humidity sensor switches are popular upgrades.",
    options: [
      { label: "Ducted exhaust fan" },
      { label: "3-in-1 unit (light + heat + exhaust)" },
      { label: "Recirculating fan" },
      { label: "Not sure" },
    ],
    multiSelect: false,
    defaultIfSkipped: "Ducted exhaust fan",
  },
  {
    id: "tiling_extent",
    question: "How much tiling?",
    why: "Full-height tiling looks premium but costs more in materials and labour. Half-height with painted walls above is a common budget option.",
    options: [
      { label: "Floor to ceiling — all walls" },
      { label: "Full height in shower, half height elsewhere" },
      { label: "Shower area only + floor" },
      { label: "Not sure" },
    ],
    multiSelect: false,
    defaultIfSkipped: "Full height in shower, half height elsewhere",
  },
  {
    id: "shower_niche",
    question: "Shower niche (recessed shelf)?",
    why: "Niches need to be framed, waterproofed, and tiled. They're best planned upfront — retrofitting is expensive.",
    options: [
      { label: "Yes — single niche" },
      { label: "Yes — double/tall niche" },
      { label: "No niche — will use corner shelf" },
      { label: "Not sure" },
    ],
    multiSelect: false,
    defaultIfSkipped: "Yes — single niche",
  },
  {
    id: "lighting",
    question: "What lighting do you want?",
    why: "Bathroom lights near showers must be IP-rated (water resistant). Mirror lighting, shower niche lighting, and general downlights all need separate planning.",
    options: [
      { label: "Downlights only" },
      { label: "Downlights + mirror/vanity lighting" },
      { label: "Downlights + LED shower niche light" },
      { label: "Not sure — open to suggestions" },
    ],
    multiSelect: true,
    defaultIfSkipped: "Downlights only",
  },
  {
    id: "quality_tier",
    question: "What quality level are you targeting?",
    why: "This sets realistic budget ranges for tiles, tapware, fixtures, and vanity. It doesn't change what work is needed — just the expected material costs.",
    options: [
      { label: "Budget ($10-20K) — functional, clean" },
      { label: "Mid-range ($20-35K) — good quality, modern look" },
      { label: "Premium ($35-55K) — high-end finishes" },
      { label: "Luxury ($55K+) — designer everything" },
    ],
    multiSelect: false,
    defaultIfSkipped: "Mid-range ($20-35K) — good quality, modern look",
  },
  {
    id: "diy_interest",
    question: "Are you interested in doing any work yourself?",
    why: "Demolition and painting are commonly DIYed in bathrooms. Plumbing, electrical, and waterproofing must be done by licensed tradies.",
    options: [
      { label: "Yes — happy to do demo and painting" },
      { label: "Maybe — tell me what's safe to DIY" },
      { label: "No — I want tradies to do everything" },
    ],
    multiSelect: false,
    defaultIfSkipped: "Maybe — tell me what's safe to DIY",
    modeOnly: "trades",
  },
];
