import type { Question } from "@/types";

export const kitchenQuestions: Question[] = [
  {
    id: "layout_change",
    question: "Are you changing the kitchen layout?",
    why: "Layout changes affect plumbing, electrical, and potentially structural work. Same-layout renovations are significantly simpler and cheaper.",
    options: [
      { label: "No — keeping same layout" },
      { label: "Minor tweaks — moving a few things" },
      { label: "Major redesign — completely different layout" },
      { label: "Not sure yet" },
    ],
    multiSelect: false,
    defaultIfSkipped: "Minor tweaks — moving a few things",
  },
  {
    id: "wall_removal",
    question: "Are any walls being removed or modified?",
    why: "Wall removal may require a structural engineer and council approval. Load-bearing walls need a steel beam, which adds significant cost.",
    options: [
      { label: "No walls being touched" },
      { label: "Removing a non-load-bearing wall" },
      { label: "Removing a wall (not sure if load-bearing)" },
      { label: "Creating a servery window or pass-through" },
    ],
    multiSelect: false,
    defaultIfSkipped: "No walls being touched",
  },
  {
    id: "cooktop_type",
    question: "What type of cooktop will you have?",
    why: "Gas and induction cooktops have very different electrical and plumbing requirements. Induction needs a dedicated high-amp circuit. Gas needs a certified gas connection.",
    options: [
      { label: "Gas — keeping existing" },
      { label: "Gas — new or relocated" },
      { label: "Induction" },
      { label: "Electric ceramic" },
      { label: "Not sure yet" },
    ],
    multiSelect: false,
    defaultIfSkipped: "Not sure yet",
  },
  {
    id: "oven_type",
    question: "What type of oven?",
    why: "Built-in wall ovens need a dedicated electrical circuit and specific cabinet housing. Freestanding ovens are simpler.",
    options: [
      { label: "Built-in wall oven" },
      { label: "Built-in wall oven + microwave tower" },
      { label: "Freestanding oven/stove" },
      { label: "Keeping existing" },
    ],
    multiSelect: false,
    defaultIfSkipped: "Built-in wall oven",
  },
  {
    id: "island_bench",
    question: "Will you have an island bench?",
    why: "Islands with sinks or cooktops need water, waste, gas, or power run through the floor — this can mean cutting into the concrete slab, which is a significant scope item.",
    options: [
      { label: "Yes — with sink" },
      { label: "Yes — with cooktop" },
      { label: "Yes — prep and seating only" },
      { label: "No island" },
    ],
    multiSelect: false,
    defaultIfSkipped: "No island",
  },
  {
    id: "benchtop_material",
    question: "Benchtop material preference?",
    why: "This determines whether you need a stone mason (engineered/natural stone) or if the cabinet maker handles it (laminate/timber). It also significantly affects budget.",
    options: [
      { label: "Engineered stone (Caesarstone, etc.)" },
      { label: "Natural stone (marble, granite)" },
      { label: "Laminate" },
      { label: "Timber" },
      { label: "Not decided yet" },
    ],
    multiSelect: false,
    defaultIfSkipped: "Engineered stone (Caesarstone, etc.)",
  },
  {
    id: "dishwasher",
    question: "Dishwasher included?",
    why: "A dishwasher needs water supply, waste connection, and a power outlet — all of which go into the plumbing and electrical scopes.",
    options: [
      { label: "Yes — new dishwasher" },
      { label: "Yes — relocating existing" },
      { label: "No dishwasher" },
    ],
    multiSelect: false,
    defaultIfSkipped: "Yes — new dishwasher",
  },
  {
    id: "rangehood",
    question: "Rangehood type?",
    why: "Ducted rangehoods need a duct run to an outside wall or roof — this affects the building scope. Recirculating models are simpler but less effective.",
    options: [
      { label: "Ducted to outside (recommended)" },
      { label: "Recirculating (no external duct)" },
      { label: "Integrated downdraft in cooktop" },
      { label: "Not sure" },
    ],
    multiSelect: false,
    defaultIfSkipped: "Ducted to outside (recommended)",
  },
  {
    id: "lighting",
    question: "What lighting do you want?",
    why: "Each lighting type adds items to the electrical scope — pendants need rough-in points, under-cabinet needs a separate circuit, etc.",
    options: [
      { label: "Downlights (recessed ceiling)" },
      { label: "Pendant lights over island/bench" },
      { label: "Under-cabinet task lighting" },
      { label: "Not sure — open to suggestions" },
    ],
    multiSelect: true,
    defaultIfSkipped: "Downlights (recessed ceiling)",
  },
  {
    id: "power_needs",
    question: "Any specific power point needs?",
    why: "Planning power points now avoids the frustration of not having enough outlets where you need them. It's cheap to add during renovation but expensive to retrofit later.",
    options: [
      { label: "Plenty of benchtop outlets" },
      { label: "USB charging points" },
      { label: "Outlet inside pantry" },
      { label: "Standard is fine" },
    ],
    multiSelect: true,
    defaultIfSkipped: "Standard is fine",
  },
  {
    id: "quality_tier",
    question: "What quality level are you targeting?",
    why: "This helps us set realistic budget allowances for materials like tiles, stone, and cabinetry. It doesn't affect the scope items — just the expected price ranges.",
    options: [
      { label: "Budget ($15-25K) — functional, basic finishes" },
      { label: "Mid-range ($25-45K) — good quality, popular brands" },
      { label: "Premium ($45-70K) — high-end finishes" },
      { label: "Luxury ($70K+) — top-tier everything" },
    ],
    multiSelect: false,
    defaultIfSkipped: "Mid-range ($25-45K) — good quality, popular brands",
  },
  {
    id: "diy_interest",
    question: "Are you interested in doing any work yourself?",
    why: "Some tasks like demolition and painting are safe and common for homeowners to DIY. We'll flag which items you could do yourself to save money.",
    options: [
      { label: "Yes — happy to do demo and painting" },
      { label: "Maybe — tell me what's safe to DIY" },
      { label: "No — I want tradies to do everything" },
    ],
    multiSelect: false,
    defaultIfSkipped: "Maybe — tell me what's safe to DIY",
    modeOnly: "trades",
  },
];
