import type { Question } from "@/types";

export const livingQuestions: Question[] = [
  {
    id: "scope_of_work",
    question: "What are you doing to the living area?",
    why: "This determines which trades are needed. A simple repaint is very different from opening up walls and replacing floors.",
    options: [
      { label: "Opening up to kitchen/dining (wall removal)" },
      { label: "New flooring throughout" },
      { label: "New lighting and electrical" },
      { label: "Complete refresh (all of the above)" },
    ],
    multiSelect: true,
    defaultIfSkipped: "Complete refresh (all of the above)",
  },
  {
    id: "wall_removal",
    question: "Are any walls being removed?",
    why: "Wall removal may require structural engineering and a steel beam. This is one of the most impactful decisions in a renovation.",
    options: [
      { label: "No walls being touched" },
      { label: "Removing a wall to open up space" },
      { label: "Creating a wider opening" },
      { label: "Not sure if wall is load-bearing" },
    ],
    multiSelect: false,
    defaultIfSkipped: "No walls being touched",
  },
  {
    id: "flooring_type",
    question: "What flooring are you installing?",
    why: "Different flooring types have different subfloor preparation requirements and involve different trades (tiler vs floor installer).",
    options: [
      { label: "Timber (engineered or solid)" },
      { label: "Tiles (porcelain or ceramic)" },
      { label: "Luxury vinyl plank (LVP)" },
      { label: "Carpet" },
      { label: "Keeping existing — sand and polish" },
      { label: "Not decided yet" },
    ],
    multiSelect: false,
    defaultIfSkipped: "Timber (engineered or solid)",
  },
  {
    id: "lighting",
    question: "What lighting changes?",
    why: "New lighting typically means new circuits, dimmer switches, and potentially new ceiling penetrations.",
    options: [
      { label: "New downlights throughout" },
      { label: "Feature pendants or chandeliers" },
      { label: "Wall sconces / accent lighting" },
      { label: "Keeping existing lighting" },
      { label: "Not sure — open to suggestions" },
    ],
    multiSelect: true,
    defaultIfSkipped: "New downlights throughout",
  },
  {
    id: "ceiling_fan",
    question: "Ceiling fans?",
    why: "Ceiling fans need a dedicated switch (sometimes with speed controller + light), and the electrical box in the ceiling must be fan-rated for the weight.",
    options: [
      { label: "Yes — with light" },
      { label: "Yes — fan only" },
      { label: "No ceiling fan" },
    ],
    multiSelect: false,
    defaultIfSkipped: "No ceiling fan",
  },
  {
    id: "entertainment",
    question: "TV and entertainment setup?",
    why: "Wall-mounted TVs need power, data, and HDMI points behind the wall. Planning this now avoids visible cables later.",
    options: [
      { label: "Wall-mounted TV (need power + data behind wall)" },
      { label: "TV on furniture (just need nearby outlet)" },
      { label: "Home theatre / surround sound wiring" },
      { label: "No special requirements" },
    ],
    multiSelect: true,
    defaultIfSkipped: "No special requirements",
  },
  {
    id: "living_features",
    question: "Any additional features?",
    why: "These features add specific trade requirements that wouldn't otherwise be included.",
    options: [
      { label: "Built-in shelving or cabinetry" },
      { label: "Fireplace (gas or electric)" },
      { label: "Wet bar or kitchenette" },
      { label: "No additional features" },
    ],
    multiSelect: true,
    defaultIfSkipped: "No additional features",
  },
  {
    id: "quality_tier",
    question: "What quality level?",
    why: "Sets budget expectations for materials and finishes.",
    options: [
      { label: "Budget ($5-15K) — fresh and functional" },
      { label: "Mid-range ($15-35K) — quality finishes" },
      { label: "Premium ($35-60K) — high-end throughout" },
      { label: "Luxury ($60K+) — designer quality" },
    ],
    multiSelect: false,
    defaultIfSkipped: "Mid-range ($15-35K) — quality finishes",
  },
  {
    id: "diy_interest",
    question: "Are you interested in doing any work yourself?",
    why: "Some tasks like demolition and painting are safe and common for homeowners to DIY. We'll flag which items you could do yourself to save money.",
    options: [
      { label: "Yes — happy to do demo and painting" },
      { label: "Maybe — tell me what's safe to DIY" },
      { label: "No — I want tradies to do everything" },
    ],
    multiSelect: false,
    defaultIfSkipped: "Maybe — tell me what's safe to DIY",
    modeOnly: "trades",
  },
];
