import type { Question } from "@/types";

export const outdoorQuestions: Question[] = [
  {
    id: "outdoor_type",
    question: "What type of outdoor space?",
    why: "Different structures have different building and trade requirements. A roofed alfresco is much more involved than an open deck.",
    options: [
      { label: "Open deck (no roof)" },
      { label: "Covered alfresco / pergola" },
      { label: "Enclosed outdoor room" },
      { label: "Patio / concrete area" },
      { label: "Combination" },
    ],
    multiSelect: false,
    defaultIfSkipped: "Covered alfresco / pergola",
  },
  {
    id: "decking_material",
    question: "Decking material?",
    why: "Timber and composite decking have different subframe requirements, maintenance, and cost profiles.",
    options: [
      { label: "Hardwood timber (Merbau, Spotted Gum)" },
      { label: "Composite decking (Trex, ModWood)" },
      { label: "Treated pine" },
      { label: "Concrete / paving" },
      { label: "Not sure yet" },
    ],
    multiSelect: false,
    defaultIfSkipped: "Hardwood timber (Merbau, Spotted Gum)",
  },
  {
    id: "outdoor_features",
    question: "What features are you including?",
    why: "Each feature brings in different trades. An outdoor kitchen needs plumbing, gas, and electrical. Lighting and fans need electrical only.",
    options: [
      { label: "Outdoor kitchen with sink" },
      { label: "BBQ area with gas connection" },
      { label: "Ceiling fan" },
      { label: "Outdoor lighting" },
    ],
    multiSelect: true,
    defaultIfSkipped: "Outdoor lighting",
  },
  {
    id: "lighting_type",
    question: "What outdoor lighting?",
    why: "Outdoor lighting needs weatherproof fittings (IP-rated). Different types have different electrical requirements.",
    options: [
      { label: "Downlights under eaves/pergola" },
      { label: "Step / stair lighting" },
      { label: "Garden and landscape lighting" },
      { label: "Security / sensor lighting" },
      { label: "No lighting needed" },
    ],
    multiSelect: true,
    defaultIfSkipped: "Downlights under eaves/pergola",
  },
  {
    id: "power_needs",
    question: "What power do you need outside?",
    why: "Outdoor power points must be weatherproof rated. EV chargers need a high-amp dedicated circuit from the switchboard.",
    options: [
      { label: "Weatherproof power points (general)" },
      { label: "EV charger provision" },
      { label: "Pool/spa power supply" },
      { label: "No outdoor power needed" },
    ],
    multiSelect: true,
    defaultIfSkipped: "Weatherproof power points (general)",
  },
  {
    id: "balustrade",
    question: "Does the deck need a balustrade (railing)?",
    why: "Australian building code requires a balustrade on any deck more than 1 metre above ground level. Material choice affects cost significantly.",
    options: [
      { label: "Yes — glass" },
      { label: "Yes — stainless steel wire" },
      { label: "Yes — timber" },
      { label: "No — ground level deck" },
      { label: "Not sure" },
    ],
    multiSelect: false,
    defaultIfSkipped: "No — ground level deck",
  },
  {
    id: "privacy",
    question: "Privacy screening needed?",
    why: "Privacy screens can be built by the carpenter as part of the deck structure, or can be a separate purchase.",
    options: [
      { label: "Yes — timber slat screening" },
      { label: "Yes — aluminium screening" },
      { label: "Yes — planting/green screen" },
      { label: "No screening needed" },
    ],
    multiSelect: false,
    defaultIfSkipped: "No screening needed",
  },
  {
    id: "drainage",
    question: "Any drainage concerns?",
    why: "Deck drainage, stormwater management, and water runoff need to be planned. Poor drainage can cause water damage to the house.",
    options: [
      { label: "Yes — area is prone to water pooling" },
      { label: "Need drainage under deck" },
      { label: "No concerns" },
      { label: "Not sure" },
    ],
    multiSelect: false,
    defaultIfSkipped: "No concerns",
  },
  {
    id: "quality_tier",
    question: "What quality level?",
    why: "Sets budget expectations for materials — especially decking and screening materials.",
    options: [
      { label: "Budget ($10-25K) — functional outdoor space" },
      { label: "Mid-range ($25-50K) — quality finishes" },
      { label: "Premium ($50-80K) — full outdoor living" },
      { label: "Luxury ($80K+) — resort-style" },
    ],
    multiSelect: false,
    defaultIfSkipped: "Mid-range ($25-50K) — quality finishes",
  },
  {
    id: "diy_interest",
    question: "Are you interested in doing any work yourself?",
    why: "Some tasks like site preparation, painting, and landscaping are safe for homeowners to DIY. We'll flag which items you could do yourself to save money.",
    options: [
      { label: "Yes — happy to do site prep and painting" },
      { label: "Maybe — tell me what's safe to DIY" },
      { label: "No — I want tradies to do everything" },
    ],
    multiSelect: false,
    defaultIfSkipped: "Maybe — tell me what's safe to DIY",
    modeOnly: "trades",
  },
];
